version: '3'
services:
  web:
    image: php:apache
    #build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "docker-php-ext-install mysqli && apache2-foreground"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: example_user_password
    volumes:
      - todo-data:/var/lib/mysql
      - ./bd:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
volumes:
  todo-data: